---
title: "Twitter IPO"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(twitteR)
library(rtweet)
library(stringr)
library(lubridate)
library(tidytext)
library(purrr)
library(readxl)
library(httpuv)
library(ROAuth)
library(RCurl)
library(openssl)
library(tidyverse)
library(dplyr)
library(ggplot2)

download.file(url='http://curl.haxx.se/ca/cacert.pem', destfile='cacert.pem')
```

# TWITTER
```{r}
# AUTHORIZATION

access_token <- "1120303734-GEPzSvsSOq4pooOg0KA5xhpYatMluCB1Zd5LIMJ"
access_token_secret <- "srfh2ElJnYTKJPZDVMlrDtv7w7MTuPvTyuiFTkcrUOW0G"
api_key <- "E8DGvieQ4TZg0GGUqHYDEwdcz"
api_key_secret <- "DqEbvxIwGgWw71PAupw2s0Q1MYYfi5Zq0BbZyXeHx7wavFyy0b"
bearer_token <- "AAAAAAAAAAAAAAAAAAAAAMrjbAEAAAAAc79%2F0X%2B7SG3dwAyiDRCp0ldfA7M%3DHwUVD9XHKhmcCQZOm2p9C0YOYfCfHg4Ug4UykUAUbj2cMD2S3M"

token <- create_token(
  app = "Econ970twitteripo",
  consumer_key = api_key,
  consumer_secret = api_key_secret)

token2 <- setup_twitter_oauth(consumer_key = api_key, consumer_secret = api_key_secret, access_token=access_token,
access_secret=access_token_secret)
```


```{r}
uber_tweets <- rtweet::get_timeline(c("uber"), n = 3000, parse=T, token = token)
rtweet::write_as_csv(uber_tweets, "uber_tweets.csv", prepend_ids = TRUE, na = "", fileEncoding = "UTF-8")
```




# IPO
```{r}
ipo2021 <- read.csv("~/Downloads/ipos-2021.csv")

ipo2021 <- ipo2021 %>%
  filter(Sector == "Technology") %>%
  mutate(IPO.Date = as.Date(IPO.Date, format = "%b %d, %Y"),
         IPO.1Mbefore = IPO.Date %m-% months(1),
         IPO.3Mbefore = IPO.Date %m-% months(3),
         short.name = gsub(",.*", "\\1",
                           gsub("Corp..*", "\\1",
                                gsub("Co..*", "\\1", 
                                     gsub("Ltd..*", "\\1", Company.Name)))))
ipo2021$short.name[ipo2021$Company.Name == "Coupang, Inc."] <- "Coupang"
ipo2021$short.name[ipo2021$Company.Name == "Compute Health Acquisition Corp."] <- "Compute Health Acquisition"

```

```{r}
twitter_handles <- read_xlsx("~/Downloads/iposignstwitter.xlsx")

ipo2021 <- full_join(twitter_handles, ipo2021, by = "Symbol")
```


```{r}
x <- ipo2021$short.name[5]
search_users(x)
test <- search_users(x) %>%
  mutate(twitter_user_id = ifelse(str_contains))

searchTwitter(x)

get_sentiments("bing")


```


```{r}
for (i in 1:nrow(ipo2021)){
  x <- ipo2021$short.name[i]
  searchTwitter(x, since=ipo2021$IPO.3Mbefore, until=ipo2021$IPO.Date)
}
```

























